# FROM THIS TO https://github.com/bertz-tech/TESTREPO



name: ğŸª CLONE COMPONENTS

on:
  push:
    branches: [ main ]

jobs:
  components-deploy:
    name: ğŸª CLONE-COMPONENTS
    runs-on: ubuntu-latest
    steps:

      - name: ğŸ” Get latest code
        uses: actions/checkout@v2
        with:
          submodules: true
