# FROM THIS TO https://github.com/bertz-tech/TESTREPO



name: ü™ê CLONE COMPONENTS

on:
  push:
    branches: [ main ]

jobs:
  components-deploy:
    name: ü™ê CLONE-COMPONENTS
    runs-on: ubuntu-latest
        container: pandoc/latex

    steps:
      - uses: actions/checkout@v2
           - name: Pushes to repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'bertz-tech'
          destination-repository-name: 'TEST-AUTOMARGE-REPO-RECEIVING'
          #user-email: carles3@pina.cat
          target-branch: main
