# FROM THIS TO https://github.com/bertz-tech/TESTREPO



name: ü™ê CLONE COMPONENTS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
        name: üóÅ Push to...
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.transfer_token }}
        with:
          source-directory: 'output'
          destination-github-username: 'bertz-tech'
          destination-repository-name: 'TEST-AUTOMARGE-REPO-RECEIVING'
          target-branch: main
